### ISSUE TITLE
성규 / Entity 생성.

### ISSUE THREAD

**Issue by seongkyu-lim** [Notherr/ParkingPpak-server#3]
- [x] enum type : navi, oilType, compName
- [x] entity, repository.
<img width="675" alt="스크린샷 2022-03-29 오후 5 14 36" src="https://user-images.githubusercontent.com/55138532/160565659-fb7bb890-89e5-41d4-a5ee-fdf297c3a0dc.png">

**Comment by HyungJunGoo** [comment]
enum 타입으로 만들면 좋을건 oil type, navi, comp_type (신한 현대 롯데 BC 우리 등등), 
또 Parking Lot의 Open Day를 다룰때도 Day 과련된 걸 enum 으로 다루면 (MON, TUE, ~~SUN) 이걸 set으로 들고 있게 하면 어떨까 싶네요?

**Comment by seongkyu-lim** [comment]
데이터를 파싱해서 저장할 때, 요일 단위로 enum타입으로 변경해서 저장하는 코드를 추가할 필요가 있겠네요, try it.

**Comment by seongkyu-lim** [comment]
account_parkinglot_list : 찜목록 목적.
