### ISSUE TITLE
성규, 형준 / 좋아요 기능 지도 데이터 반환 API에 추가

### ISSUE THREAD

**Issue by HyungJunGoo** [Notherr/ParkingPpak-server#48]
- Spring Security Filter change
    - AS-IS (현재) : filter에서는 jwt 검증만 진행.
    - TO-BE (계획) :  filter에서 jwt검증을 포함하여 jwt 복호화 및 accountId 획득 후 전달까지 하도록.
    + 검색 API에 대한 인가 필터 처리
- Elasticsearch add user favorite list dependency
add comment

**Comment by seongkyu-lim** [comment]
@HyungJunGoo 작업 코멘트 작성했슴다~
